### ISSUE TITLE
Latest Node.js versions (9.5.0)

### ISSUE THREAD

**Issue by ohenepee** [sjitech/nodejs-android-prebuilt-binaries#1]
Can you please provide prebuilt binaries for the latest version? B'cos of its performance optimizations and extensive ES7 support.

**Comment by troysyh** [comment]
Please kindly provide the v8.9.1 LTS, thanks

**Comment by liulover5** [comment]
now we hope provide V8.9.4 LTS ，haha

**Comment by bigbenz8** [comment]
A great project

**Comment by kb-1000** [comment]
You could try to work around by building it on yourself, using [https://github.com/sjitech/build-nodejs-for-android](https://github.com/sjitech/build-nodejs-for-android).

**Comment by jjqq2013** [comment]
I have built 9.11.0 for arm and arm64. But not tested yet.
